[package]
name = "aisd_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
rand = "0.9.0-alpha.1"
plotters = "0.3.6"
rand_pcg = "0.9.0-alpha.1"
rbtree = "0.2.0"
rayon = "1.10.0"

#[profile.release]
#debug = true